name: workflow update_manifesh

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
jobs:
  update_tag:
    runs-on: self-hosted
    steps:
    - name: ðŸ” GH_TOKEN
      if: env.GH_TOKEN == ''
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
    - name: ðŸ¤˜ checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ env.GH_TOKEN }}
    - name: Set variable
      run: |-
        echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV  
    - name: Is dev?
      if: env.BRANCH == 'dev' 
      run: echo "DIR=deploy/dev" >> $GITHUB_ENV;
    - name: Is develop?
      if: env.BRANCH == 'develop' 
      run: echo "DIR=deploy/dev" >> $GITHUB_ENV;
    - name: Is sit?
      if: env.BRANCH == 'sit'
      run: echo "DIR=deploy/sit" >> $GITHUB_ENV;
    - name: Is uat?
      if: env.BRANCH == 'uat'
      run: echo "DIR=deploy/uat" >> $GITHUB_ENV;
    - name: Is preprod?
      if: env.BRANCH == 'preprod'
      run: echo "DIR=deploy/pre" >> $GITHUB_ENV;
    - name: Is master?
      if: env.BRANCH == 'master'
      run: echo "DIR=deploy/production" >> $GITHUB_ENV;
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: Set Tag
      run: | 
        echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV;
        echo ${{ inputs.imagename }};
    - name: Patch kustomize
      run: |-
        cd ${{ env.DIR }}
        echo "kustomize update ${{ env.DIR }}"
        kustomize edit set image insuranceitteam/${{ inputs.imagename }}
        cat kustomization.yml

#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: ${{ env.BRANCH }}
#         message: "update Image tag"
    - name: âš™ changelog
      uses: faberNovel/github-changelog-generator-action@master
      with:
        options: --token ${{ secrets.GITHUB_TOKEN }} --o changelog.md

    - name: ðŸš€ changelog
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add changelog.md
        git commit -m "Update changelog with ${GITHUB_REF#refs/*/}"
        git push
